### ISSUE TITLE
Choosing Coffers

### ISSUE THREAD

**Issue by hhttll** [BigRedBrent/NeverwinterInvokeBot#1]
As far as I know we have to manually alter the script to choose the type of coffer we want, when a character has 14 coins - how do we do that (given I have no idea how au3 works)?

**Comment by BigRedBrent** [comment]
I will have to make a tutorial sometime to show people how to find the x, y coordinates and the hex color codes, and where to put that information in the script.

For the most part, you can take a screen shot and paste that screen shot into almost any image editor to find the information required.

**Comment by hhttll** [comment]
yeah, i gathered that but how do i code it?

any chance you can make the code for each coffer and offer it as a text file, so people can just copy-paste it into the script?

**Comment by BigRedBrent** [comment]
You have to find the x, y location of the coffer yourself. You could find the location of each and save that somewhere else and then put in the one that you decide to use in the script itself.

**Comment by hhttll** [comment]
GOD you are a retard!
i said i know that, no duh, the point was i dont know the syntax of the language, genius

**Comment by BigRedBrent** [comment]
I am not understanding your use of the phrase "code for each coffer", because there is only an option to select a single coffer location, regardless of how many coffers can be chosen from. I am sorry for being so imbecilic that I can not completely understand your so very simplistic and comprehensive explanation of your question.

I try to be a very understanding and forgiving person. But name calling? Really? When asking for my help? Seriously??? I honestly would rather be a complete moron than inconsiderate. I can't control what you do elsewhere, but please show a little more respect on this site.

**Comment by BigRedBrent** [comment]
Using image searching for most detection now.
