### ISSUE TITLE
New bot Version 3.3 - Not invoking

### ISSUE THREAD

**Issue by dexterlazy** [BigRedBrent/NeverwinterInvokeBot#10]
New bot Version 3.3 - Not invoking
It logs in and then jumps then goes to character logout.
It does not invoke.

I beleive this is the Invoke section.

Func Invoke()
    Sleep(1000)
    Send($JumpKey)
    Sleep(500)
    If Exists("CongratulationsWindow.png") Then
        If Not Exists("GrayedOutInvoke.png") Or Not ImageSearch("GrayedOutInvoke.png") Then
            For $j = 1 To 10
                FindLogInScreen()
                Send($InvokeKey)
                Sleep(500)
                For $k = 1 To 10
                    If Exists("VaultOfPietyButton.png") And ImageSearch("VaultOfPietyButton.png") Then
                        GetCoffer()
                        Return
                    ElseIf ImageSearch("CongratulationsWindow.png") Then
                        Return
                    EndIf
                    FindLogInScreen()
                    Sleep(500)
                Next
            Next
        EndIf
    Else
        For $j = 1 To 3
            Send($InvokeKey)
            Sleep(5000)
        Next
        If Exists("VaultOfPietyButton.png") And ImageSearch("VaultOfPietyButton.png") Then
            GetCoffer()
        EndIf
    EndIf
EndFunc

What is the "CongratulationsWindow.png" image from?
Is it searching for this image and not finding it?

**Comment by dexterlazy** [comment]
Must be the resolution I'm using on my PC (2560x1440).
Tried 2 different PCs with smaller resolution 1920x1280 and 1366x768 and both work out of the box perfectly. Evening logins in successfully if it gets disconnected.
Thanks

**Comment by BigRedBrent** [comment]
IN the latest version, I removed one of the images that was getting false positives, making it think that you had already invoked on a character. This was causing it to skip that character instead of trying to invoke on it.

I replaced that detection with pixel detection. The pixel detection requires the exact color though, and may need to be configured properly for each computer. This is not necessary for functionality though. If not set up properly and the character has already invoked, it will just try to invoke on that character until it reaches max invoke retries, and then move on to the next character.
