### ISSUE TITLE
Window resize issue

### ISSUE THREAD

**Issue by NumberB** [BigRedBrent/NeverwinterInvokeBot#12]
- First issue: Script always says window has moved, so it constantly re-prompts for the settings for a run but never runs, just continues back through that loop.

In the settings I have:
Global $GameWidth = 1680, $GameHeight = 1040 ;Will not check window size if set to 0

- Second issue: The script is what moved the window. I had the window at 1680x1040 and it offset X (from left) by 242 pixels and offset Y (from top) by 0 pixels. After I ran the script it moved the window to the left of my screen (X offset of 0 now instead of 242). I don't want this. I'd much prefer it to detect where my window is when the script is run and leave it there instead of moving it.

- Third, a question: What does this mean?
Global $SafeLogInX = 471, $SafeLogInY = 305 ;The X, Y coordinates for the Safe LogIn button.

safe login as in if the game logs you out and you are in client but have to login again? or something else?

Thanks again for all your hard work on this!

**Comment by BigRedBrent** [comment]
I just released a version that may or may not help with the window moving problem.

I have now made it so that it will not move the window unless it needs to when re-sizing.

The safe login prompt will popup sometimes when logging into a character, if you did not log out properly on that character. It is almost never needed, but if it ever is, it will stop the script from proceeding unless that button is pressed.
