### ISSUE TITLE
Script locks up game client since Strongholds update

### ISSUE THREAD

**Issue by shonsu02** [BigRedBrent/NeverwinterInvokeBot#17]
As the title says when I launch the script and after it asks the questions it immediately locks up the game client.  I've updated to the latest version and it still locks it up.  I don't get any errors or anything but I have to end the gameclient.exe task.

**Comment by shonsu02** [comment]
Well, I had the video settings on DX9 and when I switched them to DX11 it works.

**Comment by BigRedBrent** [comment]
Hmmm, good to know.

You might want to get the latest version that adds a login limit as well. I just recently had to change my IP address because it tried to log me in too many times. The latest version will only try to login 3 times in a row, unless you change the default setting.

I am pretty sure it takes more than 3 attempts to get you locked out, although I am not entirely sure what the limit actually is.

**Comment by shonsu02** [comment]
Excellent addition!  I had the same problem come up when the patch went live.  I ended up swapping out my router because I kept getting the same IP address (I had a new one and was going to change it anyway).  From what I've read if you wait to try to login again for 8 hours it will reset.  I didn't want to wait that long.

**Comment by BigRedBrent** [comment]
To change my IP address, I had to change the mac address in my router to another one that some other device inside my network is using. I ended up using the mac address from my cell phone. :p Most routers call this mac address cloning.

**Comment by dexterlazy** [comment]
The lock out for too many attempts lasts a couple hours. Had this happen to me.
Thanks for the update.
