### ISSUE TITLE
My characters don't invoke they only jump

### ISSUE THREAD

**Issue by foresakor** [BigRedBrent/NeverwinterInvokeBot#24]
I'm new to the bot so i'm probably missing some critical step. I input all the information and it logs in perfectly but then just jumps. It never invokes, bottom screen says (Invoking 1 of 8 / Waiting for in game screen)

Any thoughts on what i'm doing wrong?

**Comment by BigRedBrent** [comment]
It evidently is not detecting the in game screen. Try resetting the in game screen HUD to the default positions.

**Comment by foresakor** [comment]
thanks i tried that but no luck. I run 2 monitors, i tried disabling 1 (didn't restart computer) but it still didn't work. Game resizes to smaller version in top left corner. Login is good, i left all setting on script same no changes.

Should i restart after disabling monitor?

**Comment by BigRedBrent** [comment]
Not sure what to tell you other than you may need to capture the necessary images for your client.

**Comment by foresakor** [comment]
Thanks sorry for being so inexperienced with this. If I get it working I will certainly donate as you have done a great job from what I've seen.

I look at image folder but they are very small and not sure what I need to take screen capture of. I took a few with screencapture script and put in paint.

Any instruction on what images I should capture?

Thank you for your patience!!

**Comment by mystixa** [comment]
I had a similar problem. Im familiar with coding but havent done any work with this kind of script before.

Eventually the suggestion from BRB to reset my HUD did work for me, but I did look into the depths of the script a bit before hand.

You can see the pictures it uses to compare to under the images directory. I believe the one it uses to tell if you're actually in the game is the very left of your tool bar. That stylized dragon, or a piece of it is hard to recognize at first. Look at it in the game and you'll be able to pick it out in the directory. 

Another idea I have is that it might be sensitive to your screen resolution, especially since you said you were using multiple monitors. I would definitely try it under a simpler setup and then up the complexity if it works. (single monitor, then use the same resolution with your dual setup, etc.)

The function it uses basically looks at the whole (resized smaller) game screen and waits for a specific picture to appear so it knows where it is in the process. I am unsure just how picky that function is about its goals. It does have a sensitivity setting, but again Im unsure how much that helps.

**Comment by foresakor** [comment]
Thanks for all the advice mystixa it was very helpful. I'll continue to try and see if i can get it working.

**Comment by BigRedBrent** [comment]
Also in the options under the display tab, make sure that brightness is set to 100%.
