### ISSUE TITLE
Relogging

### ISSUE THREAD

**Issue by gomsnothereman** [BigRedBrent/NeverwinterInvokeBot#4]
Have you ever gotten the relogging to work brent?? i have it setup correctly, but it seems like when it goes into a "timeout" situation is when i come back and see i am logged out.. i am wondering about changing the code to after the 20 minute timeout, it does a check for the "login" screen..

I know it would be a freaking PITA, but i wonder if changing the code so you have a function that is ONLY used for current screen detection, so it returns a answer based on what "screen" it detected, instead of detecting individually throughout the entire script..
just an idea/queston

**Comment by BigRedBrent** [comment]
It seems to detect the login screen for me just fine without fail ever. Perhaps it has more to do with where you are looking for the colors on the screen. It probably would not be very difficult to add a small script that is only for screen detection, to show you what is being detected on the screen.

**Comment by BigRedBrent** [comment]
I have released a new version with a screen detection script.

**Comment by gomfedj** [comment]
i have a question for ya on the relogging portion of the script.. I noticed (using the screen detection tool you put out) that the coordinates i used for the "login" screen must be flickering or something (and i just can't see it) it would randomly say "login screen" on/off so i changed cords and pixels and it seems steady now..

i would sometimes see 3-4 relogins (or something stated like that) in the end message after the script finished running OR i paused it because it got stuck... I figured i could add in some code on the "timeout()" function to attempt to see if the loginscreen was up before it errored out.. Well it looks like in the "waitforscreen()" function you ALREADY have it checking repeatedly for the login screen by calling the "findloginscreen()" function? is that correct? reason i ask is, i figured i would "test" it finding the login screen by just leaving myself ON that screen and starting the script, however it never seemed to detect it was at that screen, it just sat at the "waiting for character select screen" text...

It LOOKS like it should work and login, however it is not, am i misreading/understanding the script code? or perhaps i am still having issues with the login screen detection... (hadn't tried to see if i can run BOTH the screen detection AND invoke script at once..)

**Comment by BigRedBrent** [comment]
They should be able to run at once, just as long as you put the screen detection in a place on the screen where it is not covering anything up. And yes, it does check for the log-in screen when waiting for a screen. Have you tried using the colors from the buttons on the bottom right of the log-in screen?

**Comment by gomfedj** [comment]
hmm i WAS using the text "Login" above the name/PW boxes.. but i moved up to using text where it says dungeons and dragons.. it is picking it up fine with the screen detection script, but invoke script just sits at "waiting for character selection screen", but i can't only 100% repeat this when i start the script while AT the login screen, otherwise earlier today i showed 6 relogin(s) though i did see another way to get hung up, i guess because i was using another VM on that machine the clicks screwed up and it didn't hit "character select" and some how went to the help screen (in game) and finally timed out after 15 minutes.. with that "timeout" box open it was never able to detect the login screen behind it (because it was darkened)

i will do some tweaking myself, your good looks perfect to me, but must be missing something somewhere..

**Comment by gomfedj** [comment]
ok.. figured it out (labeled each time you had a "waiting for character selection screen" with a note saying which function/screen it was under and was supposed to of come from... in your Start() code you have the code..

  If IsArray($SelectionScreenX) And Number($SelectionScreenX[1]) Then
        Splash("[ Waiting for Character Selection Screen ( under Start() ) ]")
        While Not FindPixels($SelectionScreenX, $SelectionScreenY, $SelectionScreenC)
            Sleep(500)
        WEnd
    EndIf

i THINK you have that simply to "check" at the beginning that the neverwinter window exists? i'm actually not sure.. but when you START the script that is the first thing it "wants" to do so it will sit there until it see's the character selection screen and never move forwards...

I thought and thought about if it was even NEEDED because you use that "position" function now that checks for a window "titled" neverwinter, and so i just removed that entire piece of code and it picked up starting at the login screen right away.. not sure if that will bite me in the rear later, do you know what exactly you had that code there??

**Comment by BigRedBrent** [comment]
For the most part, that part of the script is not needed. I will probably remove it because it is mostly redundant.

**Comment by gomfedj** [comment]
hmm if i come up with an idea on how to make sure how it clicks the right button i will let ya know.. not sure how though... but honestly i have only seen that "you were logged out after 15 minutes of inactivity" like... a handful of times maybe? over a few months now.. might be easier to ignore a misclick in that ONE instance, and simply add in a detection for that ONE window "timeout" pop up, to the "timeout()" part of the script, so yeah it might waste 15 minutes, BUT at least it detecting that window closes it then logs in and continues on..

**Comment by BigRedBrent** [comment]
Well, I added optional detection for the change character confirmation, that pops up after you click the change character button.

**Comment by BigRedBrent** [comment]
Using image searching for most detection now.
