### ISSUE TITLE
Possible changes to automatically add 7th loop if needed

### ISSUE THREAD

**Issue by gomsnothereman** [BigRedBrent/NeverwinterInvokeBot#7]
I was wondering if using the "rewards of devotion" on the 6th loop how hard it would be to "detect" if the 6th item was "greyed" out and if not automatically add an additional loop to the routine..

in otherwords i was thinking on 6th loop open "rewards of devotion" see that the ctrl-i isn't greyed out, invoke, then check to see the ctrl-i IS greyed out, and if that is true then check to see if your selected pixels in the 6th loop "rewards" are a certain "color" and if true = end and if false = add extra loop... Because once you invoke each reward they kinda "darken" in color..

The only hard part i see (only because i don't know how to do it) is you need to ONLY let it add a 7th loop once (even if it detects multiple characters without the 6th loop darkened) and you could even have it add an 8th loop perhaps if it STILL does not see the 6th rewards on the "devotion" screen darkened..

May not be an issue for most, but i do notice, out of about 20 character 5-10 of em missing the 6th loop when done, and i am not sure why honestly..  i suspect it is a timing issue, that the script logs back in on that character just a FEW SECONDS before he was ready to invoke again, so it skips him that round because it thinks it is done..

**Comment by BigRedBrent** [comment]
I think it is when it tries to select the next character it might skip one if it comes up short and accidentally does one that it has already done before. That is why I added the extra loop option, because I do not know how to detect if one gets skipped, unless I add an option to first always detect if the button is not greyed out first before it will try to invoke.

**Comment by gomfedj** [comment]
hmm i hadn't considered it might be "missing" because it was not ON the right character when it logged in... ugh no good way to know if the script did that, i mean you could be off by 1,2,3 character honestly depending on how much lag happened to hit at that moment.. 

hmm i suppose (would be a PITA) but you could put in 6 additional "detections" for EACH "invoke", for example so you it logged in on character 5, invoke 4 and checked and saw invoke 4 was already "darkened" because it logged in on wrong character, and so it backed out and RETRIED character 5 invoke 4... would have to have a limit on how many times it did that though or you could create a loop where it kept re-trying over and over, because say someone selected the wrong loop to start on, or had already invoked on that character without remembering...

I suppose trying to eliminate selecting the "wrong character" is why you put in detections for the scroll bar on the character selection screen having a max scroll up, and max scroll down pixels? (i didn't fill those out btw myself..)

**Comment by BigRedBrent** [comment]
The only reliable way that I can think of to detect if the character it logs into has already been invoked, is to have it always first check to see that the character has not already been invoked, by always checking first to see that the invoke button is active and not greyed out. If I did that, then yes, it may be fairly simple to have it retry invoking once or twice.

The max scroll up and scroll down are just to save time, so that it does not have to waste time with those extra key presses.

**Comment by gomfedj** [comment]
when i modified your script a month or more ago i had it detecting the greyed out Ctrl-I in the upper right over the GUI not the Ctrl-i on the invoke window.. that would speed up detection a bit.. i guess you could just ASSUME if it was greyed you were on the wrong character... 

though when i run an extra loop, sometimes using your setting and sometimes just saying i am on the 6th loop.. a LOT of them are already greyed out and i am only looking for the few that were "missed".. so you wouldn't want it to do that method on the extra loop..

**Comment by BigRedBrent** [comment]
That is true. Always expecting the characters to be invokeable would present a problem.

**Comment by BigRedBrent** [comment]
Can't think of a viable way to do this.
